data:
  path: ../data/my_dataset.xlsx
  target_column: 出生体重
  feature_engineering: false
  binning: false
  log_transform: false
  standardize: true
  test_size: 0.2

training:
  use_kfold: true
  k_folds: 5

ml:
  # 依次运行列表中的所有模型
  algorithms: ["KNN", "RandomForest", "XGBoost", "Ridge", "Lasso", "ElasticNet", "SVR", "KernelRidge", "ExtraTrees", "GBDT"]

  # --- 各个模型的超参数配置 ---
  knn:
    n_neighbors: 7
    weights: distance
    metric: minkowski
    p: 2
    n_jobs: -1
  random_forest:
    n_estimators: 500
    max_depth: null
    min_samples_split: 2
    min_samples_leaf: 1
    n_jobs: -1
    random_state: 42
  xgboost:
    n_estimators: 600
    learning_rate: 0.05
    max_depth: 6
    subsample: 0.8
    colsample_bytree: 0.8
    reg_lambda: 1.0
    random_state: 42
    n_jobs: -1
    tree_method: auto   # GPU版本可改为 gpu_hist
  ridge:
    alpha: 1.0
    solver: "auto"
    random_state: 42
  lasso:
    alpha: 0.001
    max_iter: 10000
    random_state: 42
  elasticnet:
    alpha: 0.001
    l1_ratio: 0.5
    max_iter: 10000
    random_state: 42
  svr:
    kernel: "rbf"
    C: 1.0
    epsilon: 0.1
  kernel_ridge:
    alpha: 1.0
    kernel: "rbf"
  extra_trees:
    n_estimators: 500
    max_depth: null
    random_state: 42
  gbdt:
    n_estimators: 500
    learning_rate: 0.05
    max_depth: 5
    random_state: 42

others:
  random_seed: 42
  save_root: ../experiments
