# ===================================================================
#                    项目配置文件 (RNN.yaml)
# ===================================================================

# -------------------------- 数据预处理配置 ---------------------------
data:
  path: '../data/my_dataset.xlsx'
  target_column: '出生体重'
  feature_engineering: false
  test_size: 0.15
  binning: True
  standardize: true
  log_transform: True

# ---------------------------- 模型配置 -----------------------------
model:
  name: 'RNN'                     # 仍使用 RNN/LSTM
  hidden_layers: [128]             # 增大隐藏层维度
  params:
    hidden_size: 128               # LSTM隐藏层大小
    num_layers: 2                  # 双层LSTM
    nonlinearity: 'tanh'           # RNN非线性，LSTM可忽略
    bidirectional: true            # 双向捕捉序列信息
    mlp_hidden: 128                # MLP head隐藏层
    init_type: 'xavier'            # 权重初始化
    dropout: 0.3                   # 防过拟合
    act: "relu"
    use_lazy_proj: false

# ---------------------------- 训练配置 -----------------------------
training:
  optimizer: 'AdamW'
  lr: 0.0003                        # 调整学习率
  batch_size: 32                    # 增大批量，充分利用GPU
  epochs: 200
  patience: 50
  use_kfold: true
  k_folds: 5
  scheduler:
    name: 'CosineAnnealingLR'
    T_0: 10
    T_mult: 2
    T_max: 200
    eta_min: 0.0001
    # ReduceLROnPlateau 参数
    patience: 25
    # ExponentialLR 参数
    gamma: 0.1
    # StepLR 参数
    step_size: 30
    # MultiStepLR参数
    milestones: [30, 80, 130]

# ---------------------------- 其他通用配置 ---------------------------
others:
  random_seed: 3407
  device: 'auto'                   # 自动选择GPU/CPU
  save_root: '../experiments'
  plot: true